name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read" # Rebuild 3
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ secrets.GCP_WIF_PROVIDER }}"
          service_account: "${{ secrets.GCP_SA_EMAIL }}"

      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit ./frontend \
            --config=./frontend/cloudbuild.yaml \
            --substitutions="_BACKEND_URL=https://burpla-api-415080714475.northamerica-northeast1.run.app",_AUTH_URL="https://burpla-ui-415080714475.northamerica-northeast1.run.app",_AUTH_SECRET="mysecret",_GITHUB_SHA="${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy burpla-ui \
            --image "northamerica-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/burpla/burpla-ui:sha-${{ github.sha }}" \
            --region "northamerica-northeast1" \
            --port 3000 \
            --allow-unauthenticated
